# Use Node.js base image
FROM node:18.18.2-alpine

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install dependencies forcefully (to skip peer conflicts)
RUN npm install --legacy-peer-deps

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
