# Use Node Alpine
FROM node:18.18.2-alpine

# Set working directory
WORKDIR /app

# Copy package files first to cache deps
COPY package*.json ./

# Install dependencies with legacy-peer-deps
RUN npm install --legacy-peer-deps

# Copy the rest of the app
COPY . .

# Build the app
RUN npm run build

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "start"]
